{
 "title": "Promtail & Loki dashboard",
 "description": "Loki and Promtail metrics.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "target_env",
    "label": "Environment:",
    "query": {
     "query": "label_values(promtail_build_info, target_env)"
    }
   },
   {
    "name": "target_resource_name",
    "label": "Resource Name:",
    "query": {
     "query": "label_values(promtail_build_info{target_env=\"$target_env\"}, target_resource_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Promtail (Host)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of bytes total by promtail",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (promtail_file_bytes_total{target_resource_name=~\"$target_resource_name\"}) by (target_resource_name)",
     "legendFormat": "{{target_resource_name}}"
    }
   ]
  },
  {
   "title": "Number of bytes encoded and ready to send by Promtail",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (promtail_encoded_bytes_total{pod=~'.*',target_resource_name=~\"$target_resource_name\"}) by (target_resource_name,pod)",
     "legendFormat": "{{target_resource_name}} {{ pod }}"
    }
   ]
  },
  { "title": "Loki (Monitoring host)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Loki's stored chunk entries",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(loki_ingester_chunk_entries_count[5m])",
     "legendFormat": "{{target_resource_name}}"
    }
   ]
  },
  {
   "title": "Average batch appends sent to ingesters (Loki)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (loki_distributor_ingester_appends_total[5m])",
     "legendFormat": "{{target_resource_name}}"
    }
   ]
  }
 ]
}