{
 "title": "System statistics (Windows exporter dashboard)",
 "description": "General stats dashboard windows_exporter.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "target_env",
    "label": "Environment:",
    "query": {
     "query": "label_values(node_uname_info, target_env)"
    }
   },
   {
    "name": "target_resource_name",
    "label": "Resource Name:",
    "query": {
     "query": "label_values(windows_system_system_up_time{target_env=\"$target_env\"}, target_resource_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (target_resource_name) (irate(windows_cpu_time_total{mode=\"idle\", target_resource_name=~\"$target_resource_name\"}[1m])) * 100) > 0"
    }
   ]
  },
  {
   "title": "Physical memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_cs_physical_memory_bytes{target_resource_name=~\"$target_resource_name\"} - windows_os_physical_memory_free_bytes{target_resource_name=~\"$target_resource_name\"}) / windows_cs_physical_memory_bytes{target_resource_name=~\"$target_resource_name\"} * 100"
    }
   ]
  },
  {
   "title": "Virtual memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_os_virtual_memory_bytes{target_resource_name=~\"$target_resource_name\"} - windows_os_virtual_memory_free_bytes{target_resource_name=~\"$target_resource_name\"}) / windows_os_virtual_memory_bytes{target_resource_name=~\"$target_resource_name\"} * 100"
    }
   ]
  },
  {
   "title": "C: space used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_logical_disk_size_bytes{target_resource_name=~\"$target_resource_name\", volume=\"C:\"} - windows_logical_disk_free_bytes{target_resource_name=~\"$target_resource_name\", volume=\"C:\"}) / windows_logical_disk_size_bytes{target_resource_name=~\"$target_resource_name\", volume=\"C:\"} * 100"
    }
   ]
  },
  {
   "title": "Net utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sum(irate(windows_net_bytes_total{target_resource_name=~\"$target_resource_name\"}[5m])) / sum(windows_net_current_bandwidth{target_resource_name=~\"$target_resource_name\"}/8) * 100"
    }
   ]
  },
  { "title": "Cpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU load %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "100 / sum(rate(windows_cpu_time_total{target_resource_name=~\"$target_resource_name\"}[1m])) * sum(rate(windows_cpu_time_total{target_resource_name=~\"$target_resource_name\", mode=\"dpc\"}[1m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "dpc",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "100 / sum(rate(windows_cpu_time_total{target_resource_name=~\"$target_resource_name\"}[1m])) * sum(rate(windows_cpu_time_total{target_resource_name=~\"$target_resource_name\", mode=\"interrupt\"}[1m]))",
     "legendFormat": "interrupt"
    },
    {
     "expr": "100 / sum(rate(windows_cpu_time_total{target_resource_name=~\"$target_resource_name\"}[1m])) * sum(rate(windows_cpu_time_total{target_resource_name=~\"$target_resource_name:9182.*\", mode=\"privileged\"}[1m]))",
     "legendFormat": "privileged"
    },
    {
     "expr": "100 / sum(rate(windows_cpu_time_total{target_resource_name=~\"$target_resource_name\"}[1m])) * sum(rate(windows_cpu_time_total{target_resource_name=~\"$target_resource_name\", mode=\"user\"}[1m]))",
     "legendFormat": "user"
    },
    {
     "expr": "100 / sum(rate(windows_cpu_time_total{target_resource_name=~\"$target_resource_name\"}[1m])) * sum(rate(windows_cpu_time_total{target_resource_name=~\"$target_resource_name\", mode=\"idle\"}[1m]))",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "CPU load by cpu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (mode) (rate(windows_cpu_time_total{target_resource_name=~\"$target_resource_name\", mode !~ \"idle\"}[1m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{mode}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU load per process",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "CPU load" }
   ],
   "targets": [
    {
     "expr": "sum by (process) (rate(windows_process_cpu_time_total{target_resource_name=~\"$target_resource_name\", process !~\"Idle\"}[1m]))",
     "legendFormat": "{{ process }}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{target_resource_name=~\"$target_resource_name\"} - windows_os_physical_memory_free_bytes{target_resource_name=~\"$target_resource_name\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes{target_resource_name=~\"$target_resource_name\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Average commit bytes per process",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (process) (windows_process_private_bytes{target_resource_name=~\"$target_resource_name\", process=~\".*\"})",
     "legendFormat": "{{ process }}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Hard drive load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_write_bytes_total{target_resource_name=~\"$target_resource_name\", volume !~\"HarddiskVolume.+\"}[1m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_read_bytes_total{target_resource_name=~\"$target_resource_name\", volume !~\"HarddiskVolume.+\"}[1m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Hard disk i/o ops total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_logical_disk_split_ios_total{target_resource_name=~\"$target_resource_name\", volume !~\"HarddiskVolume.+\"}[1m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "i/o {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Hard disk used space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(windows_logical_disk_size_bytes{target_resource_name=~\"$target_resource_name\", volume !~\"HarddiskVolume.+\"} - windows_logical_disk_free_bytes{target_resource_name=~\"$target_resource_name\", volume !~\"HarddiskVolume.+\"}) / windows_logical_disk_size_bytes{target_resource_name=~\"$target_resource_name\", volume !~\"HarddiskVolume.+\"} * 100",
     "legendFormat": "used {{volume}}"
    }
   ]
  },
  {
   "title": "HDD free size",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{target_resource_name=~\"$target_resource_name\", volume !~\"HarddiskVolume.+\"}"
    }
   ]
  },
  {
   "title": "I/o bytes total per process",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (process) (rate(windows_process_io_bytes_total{target_resource_name=~\"$target_resource_name\", mode=\"read\"}[1m])) >0",
     "legendFormat": "{{ process }} read"
    },
    {
     "expr": "- avg by (process) (rate(windows_process_io_bytes_total{target_resource_name=~\"$target_resource_name\", mode=\"write\"}[1m])) <0",
     "legendFormat": "{{ process }} write"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Network discarded/error packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_outbound_discarded{target_resource_name=~\"$target_resource_name\", nic!~\"isatap.+\"}[1m]) + irate(windows_net_packets_outbound_errors{target_resource_name=~\"$target_resource_name\"}[1m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Sent {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_received_discarded{target_resource_name=~\"$target_resource_name\", nic!~\"isatap.+\"}[1m]) + irate(windows_net_packets_received_errors{target_resource_name=~\"$target_resource_name\"}[1m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_bytes_sent_total{target_resource_name=~\"$target_resource_name\"}[1m]) >0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Sent {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- rate(windows_net_bytes_received_total{target_resource_name=~\"$target_resource_name\"}[1m]) <0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "System exception dispatches",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_system_exception_dispatches_total{target_resource_name=~\"$target_resource_name\"}[1m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "exceptions",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "system_threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_system_threads{target_resource_name=~\"$target_resource_name\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "system_threads",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Services by state",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(windows_service_state{target_resource_name=~\"$target_resource_name\"}) by (state)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{state}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}