{
 "title": "Docker & containers dashboard (cadvisor)",
 "description": "Dashboard with details of the container metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datacenter", "label": "datacenter", "query": "IAD*" },
   {
    "name": "target_env",
    "label": "Environment:",
    "query": {
     "query": "label_values(cadvisor_version_info, target_env)"
    }
   },
   {
    "name": "target_resource_name",
    "label": "Resource Name:",
    "query": {
     "query": "label_values(cadvisor_version_info{target_env=~\"$target_env\"}, target_resource_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{target_resource_name=~\"$target_resource_name\"}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{id=~\"/docker/.*\",target_resource_name=~\"$target_resource_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Disk space /",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes{fstype=~\"xfs|ext4\",target_resource_name=~\"$target_resource_name\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext4\",target_resource_name=~\"$target_resource_name\"} )/ node_filesystem_size_bytes{fstype=~\"xfs|ext4\",target_resource_name=~\"$target_resource_name\"})",
     "legendFormat": "/"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{target_resource_name=~\"$target_resource_name\"} - node_memory_MemAvailable_bytes{target_resource_name=~\"$target_resource_name\"}) / node_memory_MemTotal_bytes{target_resource_name=~\"$target_resource_name\"}) * 100"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{target_resource_name=~'$target_resource_name'} - node_memory_SwapFree_bytes{target_resource_name=~'$target_resource_name'})"
    }
   ]
  },
  {
   "title": "Load1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_load1{target_resource_name=~\"$target_resource_name\"}) by (target_resource_name) / count(node_cpu_seconds_total{mode=\"system\",target_resource_name=~\"$target_resource_name\"}) by (target_resource_name) * 100",
     "legendFormat": "Load1"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\",target_resource_name=~\"$target_resource_name\"}[5m])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\",target_resource_name=~\"$target_resource_name\"}[5m  ])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (target_resource_name) (irate(node_cpu_seconds_total{target_resource_name=~\"$target_resource_name\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Load 1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1{target_resource_name=~\"$target_resource_name\"}) by (target_resource_name) / count(node_cpu_seconds_total{mode=\"system\",target_resource_name=~\"$target_resource_name\"}) by (target_resource_name) * 100"
    }
   ]
  },
  {
   "title": "Used Disk Space /",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype=\"ext4\",target_resource_name=~\"$target_resource_name\"} - node_filesystem_free_bytes{fstype=\"ext4\",target_resource_name=~\"$target_resource_name\"}",
     "legendFormat": "Used Disk Space"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{target_resource_name=~\"$target_resource_name\"}",
     "legendFormat": "Available memory"
    },
    {
     "expr": "node_memory_MemFree_bytes{target_resource_name=~\"$target_resource_name\"}",
     "legendFormat": "Free memory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{target_resource_name=~\"$target_resource_name\"}",
     "legendFormat": "Total memory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{target_resource_name=~\"$target_resource_name\"}-(node_memory_Buffers_bytes{target_resource_name=~\"$target_resource_name\"}+node_memory_Cached_bytes{target_resource_name=~\"$target_resource_name\"}+node_memory_MemFree_bytes{target_resource_name=~\"$target_resource_name\"})",
     "legendFormat": "Used memory"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(node_disk_read_bytes_total{target_resource_name=~\"$target_resource_name\"}[5m])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{target_resource_name=~\"$target_resource_name\"}[5m])) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name!=\"\",target_resource_name=~\"$target_resource_name\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name!=\"\",target_resource_name=~\"$target_resource_name\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\",target_resource_name=~\"$target_resource_name\"}[5m])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RSS Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name!=\"\",target_resource_name=~\"$target_resource_name\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Used Memory per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\",target_resource_name=~\"$target_resource_name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Available Memory per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_spec_memory_limit_bytes{name!=\"\",target_resource_name=~\"$target_resource_name\"}-container_memory_usage_bytes{name!=\"\",target_resource_name=~\"$target_resource_name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Limit Memory per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_spec_memory_limit_bytes{name!=\"\",target_resource_name=~\"$target_resource_name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{name!=\"\",target_resource_name=~\"$target_resource_name\"}) by (name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{name!=\"\",target_resource_name=~\"$target_resource_name\"}-container_memory_usage_bytes{name!=\"\",target_resource_name=~\"$target_resource_name\"})by (name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{name!=\"\",target_resource_name=~\"$target_resource_name\"}) by (name)"
    }
   ]
  }
 ]
}